# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MISLAND/gui\DlgSettingsEditForgotPassword.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DlgSettingsEditForgotPassword(object):
    def setupUi(self, DlgSettingsEditForgotPassword):
        DlgSettingsEditForgotPassword.setObjectName("DlgSettingsEditForgotPassword")
        DlgSettingsEditForgotPassword.resize(218, 128)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(DlgSettingsEditForgotPassword.sizePolicy().hasHeightForWidth())
        DlgSettingsEditForgotPassword.setSizePolicy(sizePolicy)
        self.verticalLayout = QtWidgets.QVBoxLayout(DlgSettingsEditForgotPassword)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(DlgSettingsEditForgotPassword)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.email = QtWidgets.QLineEdit(DlgSettingsEditForgotPassword)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.email.sizePolicy().hasHeightForWidth())
        self.email.setSizePolicy(sizePolicy)
        self.email.setMinimumSize(QtCore.QSize(200, 0))
        self.email.setInputMethodHints(QtCore.Qt.ImhEmailCharactersOnly)
        self.email.setObjectName("email")
        self.verticalLayout.addWidget(self.email)
        self.buttonBox = QtWidgets.QDialogButtonBox(DlgSettingsEditForgotPassword)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(DlgSettingsEditForgotPassword)
        QtCore.QMetaObject.connectSlotsByName(DlgSettingsEditForgotPassword)

    def retranslateUi(self, DlgSettingsEditForgotPassword):
        _translate = QtCore.QCoreApplication.translate
        DlgSettingsEditForgotPassword.setWindowTitle(_translate("DlgSettingsEditForgotPassword", "Forgot password"))
        self.label.setText(_translate("DlgSettingsEditForgotPassword", "Enter your email address below and if you have an account an email will be sent to you (from api@trends.earth) with a new password."))
        self.email.setPlaceholderText(_translate("DlgSettingsEditForgotPassword", "Enter your email address..."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DlgSettingsEditForgotPassword = QtWidgets.QDialog()
    ui = Ui_DlgSettingsEditForgotPassword()
    ui.setupUi(DlgSettingsEditForgotPassword)
    DlgSettingsEditForgotPassword.show()
    sys.exit(app.exec_())
