# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DlgSoilErosion.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DlgSoilErosion(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(283, 159)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.pushButton_fl = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_fl.sizePolicy().hasHeightForWidth())
        self.pushButton_fl.setSizePolicy(sizePolicy)
        self.pushButton_fl.setMinimumSize(QtCore.QSize(0, 48))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_fl.setFont(font)
        self.pushButton_fl.setObjectName("pushButton_fl")
        self.verticalLayout_2.addWidget(self.pushButton_fl)
        self.pushButton_fc = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_fc.sizePolicy().hasHeightForWidth())
        self.pushButton_fc.setSizePolicy(sizePolicy)
        self.pushButton_fc.setMinimumSize(QtCore.QSize(0, 48))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_fc.setFont(font)
        self.pushButton_fc.setObjectName("pushButton_fc")
        self.verticalLayout_2.addWidget(self.pushButton_fc)
        self.verticalLayout.addWidget(self.groupBox)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.groupBox.setTitle(_translate("Dialog", "Soil Erosion"))
        self.pushButton_fl.setText(_translate("Dialog", "Water Erosion"))
        self.pushButton_fc.setText(_translate("Dialog", "Wind Erosion"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_DlgSoilErosion()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
