# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MISLAND/gui\DlgSettingsAdvanced.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DlgSettingsAdvanced(object):
    def setupUi(self, DlgSettingsAdvanced):
        DlgSettingsAdvanced.setObjectName("DlgSettingsAdvanced")
        DlgSettingsAdvanced.resize(412, 218)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(DlgSettingsAdvanced.sizePolicy().hasHeightForWidth())
        DlgSettingsAdvanced.setSizePolicy(sizePolicy)
        self.verticalLayout = QtWidgets.QVBoxLayout(DlgSettingsAdvanced)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox_2 = QtWidgets.QGroupBox(DlgSettingsAdvanced)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.debug_checkbox = QtWidgets.QCheckBox(self.groupBox_2)
        self.debug_checkbox.setObjectName("debug_checkbox")
        self.verticalLayout_2.addWidget(self.debug_checkbox)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.binaries_checkbox = QtWidgets.QGroupBox(DlgSettingsAdvanced)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.binaries_checkbox.sizePolicy().hasHeightForWidth())
        self.binaries_checkbox.setSizePolicy(sizePolicy)
        self.binaries_checkbox.setCheckable(True)
        self.binaries_checkbox.setChecked(False)
        self.binaries_checkbox.setObjectName("binaries_checkbox")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.binaries_checkbox)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.binaries_folder = QtWidgets.QLineEdit(self.binaries_checkbox)
        self.binaries_folder.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.binaries_folder.sizePolicy().hasHeightForWidth())
        self.binaries_folder.setSizePolicy(sizePolicy)
        self.binaries_folder.setMinimumSize(QtCore.QSize(120, 30))
        self.binaries_folder.setReadOnly(True)
        self.binaries_folder.setObjectName("binaries_folder")
        self.horizontalLayout_2.addWidget(self.binaries_folder)
        self.binaries_browse_button = QtWidgets.QPushButton(self.binaries_checkbox)
        self.binaries_browse_button.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.binaries_browse_button.sizePolicy().hasHeightForWidth())
        self.binaries_browse_button.setSizePolicy(sizePolicy)
        self.binaries_browse_button.setMinimumSize(QtCore.QSize(0, 30))
        self.binaries_browse_button.setMaximumSize(QtCore.QSize(80, 16777215))
        self.binaries_browse_button.setObjectName("binaries_browse_button")
        self.horizontalLayout_2.addWidget(self.binaries_browse_button)
        self.binaries_download_button = QtWidgets.QPushButton(self.binaries_checkbox)
        self.binaries_download_button.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.binaries_download_button.sizePolicy().hasHeightForWidth())
        self.binaries_download_button.setSizePolicy(sizePolicy)
        self.binaries_download_button.setMinimumSize(QtCore.QSize(0, 30))
        self.binaries_download_button.setMaximumSize(QtCore.QSize(80, 16777215))
        self.binaries_download_button.setObjectName("binaries_download_button")
        self.horizontalLayout_2.addWidget(self.binaries_download_button)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.binaries_label = QtWidgets.QLabel(self.binaries_checkbox)
        self.binaries_label.setAlignment(QtCore.Qt.AlignCenter)
        self.binaries_label.setObjectName("binaries_label")
        self.verticalLayout_3.addWidget(self.binaries_label)
        self.verticalLayout.addWidget(self.binaries_checkbox)
        self.buttonBox = QtWidgets.QDialogButtonBox(DlgSettingsAdvanced)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonBox.sizePolicy().hasHeightForWidth())
        self.buttonBox.setSizePolicy(sizePolicy)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(DlgSettingsAdvanced)
        QtCore.QMetaObject.connectSlotsByName(DlgSettingsAdvanced)

    def retranslateUi(self, DlgSettingsAdvanced):
        _translate = QtCore.QCoreApplication.translate
        DlgSettingsAdvanced.setWindowTitle(_translate("DlgSettingsAdvanced", "Update user"))
        self.groupBox_2.setTitle(_translate("DlgSettingsAdvanced", "Advanced options"))
        self.debug_checkbox.setText(_translate("DlgSettingsAdvanced", "Debug mode (saves detailed logging information)"))
        self.binaries_checkbox.setTitle(_translate("DlgSettingsAdvanced", "Use binaries for faster processing"))
        self.binaries_folder.setPlaceholderText(_translate("DlgSettingsAdvanced", "Click \"Browse\" to choose a folder..."))
        self.binaries_browse_button.setText(_translate("DlgSettingsAdvanced", "Browse"))
        self.binaries_download_button.setText(_translate("DlgSettingsAdvanced", "Download"))
        self.binaries_label.setText(_translate("DlgSettingsAdvanced", "placeholder for label"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DlgSettingsAdvanced = QtWidgets.QDialog()
    ui = Ui_DlgSettingsAdvanced()
    ui.setupUi(DlgSettingsAdvanced)
    DlgSettingsAdvanced.show()
    sys.exit(app.exec_())
