# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DlgSoilErosion.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DlgSoilErosion(object):
    def setupUi(self, DlgSoilErosion):
        DlgSoilErosion.setObjectName("DlgSoilErosion")
        DlgSoilErosion.resize(283, 159)
        self.verticalLayout = QtWidgets.QVBoxLayout(DlgSoilErosion)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(DlgSoilErosion)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.WaterPushButton = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.WaterPushButton.sizePolicy().hasHeightForWidth())
        self.WaterPushButton.setSizePolicy(sizePolicy)
        self.WaterPushButton.setMinimumSize(QtCore.QSize(0, 48))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.WaterPushButton.setFont(font)
        self.WaterPushButton.setObjectName("WaterPushButton")
        self.verticalLayout_2.addWidget(self.WaterPushButton)
        self.WindPushButton = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.WindPushButton.sizePolicy().hasHeightForWidth())
        self.WindPushButton.setSizePolicy(sizePolicy)
        self.WindPushButton.setMinimumSize(QtCore.QSize(0, 48))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.WindPushButton.setFont(font)
        self.WindPushButton.setObjectName("WindPushButton")
        self.verticalLayout_2.addWidget(self.WindPushButton)
        self.verticalLayout.addWidget(self.groupBox)

        self.retranslateUi(DlgSoilErosion)
        QtCore.QMetaObject.connectSlotsByName(DlgSoilErosion)

    def retranslateUi(self, DlgSoilErosion):
        _translate = QtCore.QCoreApplication.translate
        DlgSoilErosion.setWindowTitle(_translate("DlgSoilErosion", "Dialog"))
        self.groupBox.setTitle(_translate("DlgSoilErosion", "Soil Erosion"))
        self.WaterPushButton.setText(_translate("DlgSoilErosion", "Water Erosion"))
        self.WindPushButton.setText(_translate("DlgSoilErosion", "Wind Erosion"))
