# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MISLAND/gui\DlgSettingsEdit.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DlgSettingsEdit(object):
    def setupUi(self, DlgSettingsEdit):
        DlgSettingsEdit.setObjectName("DlgSettingsEdit")
        DlgSettingsEdit.resize(199, 197)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(DlgSettingsEdit.sizePolicy().hasHeightForWidth())
        DlgSettingsEdit.setSizePolicy(sizePolicy)
        self.verticalLayout = QtWidgets.QVBoxLayout(DlgSettingsEdit)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(DlgSettingsEdit)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.pushButton_change_user = QtWidgets.QPushButton(DlgSettingsEdit)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_change_user.sizePolicy().hasHeightForWidth())
        self.pushButton_change_user.setSizePolicy(sizePolicy)
        self.pushButton_change_user.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButton_change_user.setObjectName("pushButton_change_user")
        self.verticalLayout.addWidget(self.pushButton_change_user)
        self.pushButton_update_profile = QtWidgets.QPushButton(DlgSettingsEdit)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_update_profile.sizePolicy().hasHeightForWidth())
        self.pushButton_update_profile.setSizePolicy(sizePolicy)
        self.pushButton_update_profile.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_update_profile.setFont(font)
        self.pushButton_update_profile.setObjectName("pushButton_update_profile")
        self.verticalLayout.addWidget(self.pushButton_update_profile)
        self.pushButton_delete_user = QtWidgets.QPushButton(DlgSettingsEdit)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_delete_user.sizePolicy().hasHeightForWidth())
        self.pushButton_delete_user.setSizePolicy(sizePolicy)
        self.pushButton_delete_user.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_delete_user.setFont(font)
        self.pushButton_delete_user.setObjectName("pushButton_delete_user")
        self.verticalLayout.addWidget(self.pushButton_delete_user)
        self.buttonBox = QtWidgets.QDialogButtonBox(DlgSettingsEdit)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonBox.sizePolicy().hasHeightForWidth())
        self.buttonBox.setSizePolicy(sizePolicy)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(DlgSettingsEdit)
        QtCore.QMetaObject.connectSlotsByName(DlgSettingsEdit)

    def retranslateUi(self, DlgSettingsEdit):
        _translate = QtCore.QCoreApplication.translate
        DlgSettingsEdit.setWindowTitle(_translate("DlgSettingsEdit", "Update user"))
        self.label.setText(_translate("DlgSettingsEdit", "Use the options below to login with a different user, update your profile, or delete your account."))
        self.pushButton_change_user.setText(_translate("DlgSettingsEdit", "Change user"))
        self.pushButton_update_profile.setText(_translate("DlgSettingsEdit", "Update profile"))
        self.pushButton_delete_user.setText(_translate("DlgSettingsEdit", "Delete user"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DlgSettingsEdit = QtWidgets.QDialog()
    ui = Ui_DlgSettingsEdit()
    ui.setupUi(DlgSettingsEdit)
    DlgSettingsEdit.show()
    sys.exit(app.exec_())
