# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DlgSDG.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DlgSDG(object):
    def setupUi(self, DlgSDG):
        DlgSDG.setObjectName("DlgSDG")
        DlgSDG.resize(282, 270)
        self.verticalLayout = QtWidgets.QVBoxLayout(DlgSDG)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(DlgSDG)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.pushButton_lp = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_lp.sizePolicy().hasHeightForWidth())
        self.pushButton_lp.setSizePolicy(sizePolicy)
        self.pushButton_lp.setMinimumSize(QtCore.QSize(0, 48))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_lp.setFont(font)
        self.pushButton_lp.setObjectName("pushButton_lp")
        self.verticalLayout_2.addWidget(self.pushButton_lp)
        self.pushButton_lc = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_lc.sizePolicy().hasHeightForWidth())
        self.pushButton_lc.setSizePolicy(sizePolicy)
        self.pushButton_lc.setMinimumSize(QtCore.QSize(0, 48))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_lc.setFont(font)
        self.pushButton_lc.setObjectName("pushButton_lc")
        self.verticalLayout_2.addWidget(self.pushButton_lc)
        self.pushButton_cs = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_cs.sizePolicy().hasHeightForWidth())
        self.pushButton_cs.setSizePolicy(sizePolicy)
        self.pushButton_cs.setMinimumSize(QtCore.QSize(0, 48))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_cs.setFont(font)
        self.pushButton_cs.setObjectName("pushButton_cs")
        self.verticalLayout_2.addWidget(self.pushButton_cs)
        self.pushButton_sdg = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_sdg.sizePolicy().hasHeightForWidth())
        self.pushButton_sdg.setSizePolicy(sizePolicy)
        self.pushButton_sdg.setMinimumSize(QtCore.QSize(0, 48))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_sdg.setFont(font)
        self.pushButton_sdg.setObjectName("pushButton_sdg")
        self.verticalLayout_2.addWidget(self.pushButton_sdg)
        self.verticalLayout.addWidget(self.groupBox)

        self.retranslateUi(DlgSDG)
        QtCore.QMetaObject.connectSlotsByName(DlgSDG)

    def retranslateUi(self, DlgSDG):
        _translate = QtCore.QCoreApplication.translate
        DlgSDG.setWindowTitle(_translate("DlgSDG", "SDG Indicators"))
        self.groupBox.setTitle(_translate("DlgSDG", "Land Degradation Indicator"))
        self.pushButton_lp.setText(_translate("DlgSDG", "Land Productivity"))
        self.pushButton_lc.setText(_translate("DlgSDG", "Land Cover"))
        self.pushButton_cs.setText(_translate("DlgSDG", "Carbon Stock"))
        self.pushButton_sdg.setText(_translate("DlgSDG", "SDG Indicator"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DlgSDG = QtWidgets.QDialog()
    ui = Ui_DlgSDG()
    ui.setupUi(DlgSDG)
    DlgSDG.show()
    sys.exit(app.exec_())
